### ISSUE TITLE
Ruby capstone - Setup Kanban board

### ISSUE THREAD

**Issue by ReshyResh** [ReshyResh/Ruby-Items-Catalog#23]
### Link to the project: [click here](https://github.com/ReshyResh/Ruby-Items-Catalog/projects/1)

 Number of students in the team: 3
  - Student 1: Robert Baiesita (@ReshyResh)
  - Student 2: Adedamola Shittu (@DammyShittu)
  - Student 3: Faizan Zahid (@faizi2500

**Comment by mikethreels** [comment]
Hi Team, 

Your project is complete!  There is nothing else to say other than... it's time to merge it 🚀 :
Congratulations! 🎉 

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by DammyShittu** [comment]
Thank you for the review, @mikethreels 👍
